openapi: 3.0.3
info:
  title: Auth
  version: 1.0.0
  description: >
    You can use this module
servers:
  - url: http://localhost/auth/
    description: Local development server

paths:
  /health:
    get:
      summary: Application health check
      description: Checks the health status of the application and connected services.
      tags:
        - Health
      responses:
        '200':
          description: Application is healthy
          content:
            application/json:
              schema:
                type: object
                example:
                  status: ok
        '500':
          description: Service is unavailable
