name: pi-knu-dev

services:
  postgres:
    container_name: postgres-dev
    image: postgres:16.3
    env_file:
      - ../postgres/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - auth

  auth:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: auth-service
    working_dir: /auth
    volumes:
      - ../auth/auth/:/auth
    command: [ "dotnet", "run", "--urls", "http://0.0.0.0:5010" ]
    env_file:
      - ../auth/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5010/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - postgres


networks:
  app-network:
    driver: bridge
