events {}

http {
    server {
        listen 80;

        location /health {
            default_type text/plain;
            return 200;
        }

       location /auth/ {
           proxy_pass         http://auth:5010/;
           proxy_http_version 1.1;
           proxy_set_header   Upgrade $http_upgrade;
           proxy_set_header   Connection keep-alive;
           proxy_set_header   Host $host;
           proxy_cache_bypass $http_upgrade;
       }

       location /notification/ {
          allow 172.18.0.0/16;
          deny all;

          proxy_pass         http://notification:5012/;
          proxy_http_version 1.1;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection keep-alive;
          proxy_set_header   Host $host;
          proxy_cache_bypass $http_upgrade;
      }
    }
}
